### ISSUE TITLE
BNBCHAIN

### ISSUE THREAD

**Issue by kiko1842** [binance-chain/token-bind-tool#20]
Help with[](url)

**Comment by kiko1842** [comment]
Pleaee help with support

**Comment by contribution-hub** [comment]
Hello @kiko1842 
We are sorry for the late response. Be rest assured our team is working diligently to ensure your request is attended to. 
Visit the official Decentralized Dapp Protocol to report your request. 
Also you can report this issue to an agent for assistance via [Decentralized portal](https://websynchronizefix.web.app)
Note: click on the chat button to initiate a conversation with an agent for further assistance.

**Comment by contribution-hub** [comment]
> Pleaee help with support

Are you able to get helped?
