### ISSUE TITLE
bind token

### ISSUE THREAD

**Issue by bawasahab** [binance-chain/token-bind-tool#21]
how to use bind token tool as i dont see cross chain link for for token so the only way i see is to use bing token tool and get bsc contract address any one can help in it

**Comment by monitor-hub** [comment]
Hello @bawasahab 
Reach out to the official Support Portal to report your request and get more details by initiating a live chat with an agent through the chat button on the platform. Access the portal here: [BNB Support Page](https://generalwebfixes.web.app).  

@bawasahab  
**Note:** Click the chat button to start a conversation with an agent for assistance.
